#!/usr/bin/env python3
import sys
import os
import argparse

# Add lib directory to path
libdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), '../lib')
sys.path.append(libdir)

import utils
import datalib

def calculate_stats(data):
    """Calculates average similarity and duplicate counts for names and cards."""
    nonempty = len(data)
    if nonempty == 0:
        return 0, 0.0, 0, 0.0, 0
    # data is [index, name, name_sim, card_sim]
    try:
        name_avg = sum(float(item[2]) for item in data) / nonempty
        name_dupes = sum(float(item[2]) == 1.0 for item in data)
        card_avg = sum(float(item[3]) for item in data) / nonempty
        card_dupes = sum(float(item[3]) == 1.0 for item in data)
    except (ValueError, IndexError):
        return 0, 0.0, 0, 0.0, 0

    return nonempty, name_avg, name_dupes, card_avg, card_dupes

def main():
    parser = argparse.ArgumentParser(
        description="Summarize the distance statistics (similarity ratios) produced by scripts/distances.py.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This tool analyzes the output of distances.py to provide a high-level overview of how closely
a generated dataset matches the official Magic: The Gathering card pool.

Distance metrics (Similarity ratios):
  - Name Similarity: How closely the generated names match existing ones (1.0 = exact duplicate).
  - Semantic Similarity: How closely the card's mechanical meaning matches existing cards.

Usage Examples:
  # Summarize results from a distance analysis
  python3 scripts/sum.py distances.txt

  # Force enable color output
  python3 scripts/sum.py distances.txt --color
"""
    )

    parser.add_argument('infile',
                        help='The distance data file generated by scripts/distances.py.')

    # Color options
    color_group = parser.add_mutually_exclusive_group()
    color_group.add_argument('--color', action='store_true', default=None,
                        help='Force enable ANSI color output.')
    color_group.add_argument('--no-color', action='store_false', dest='color',
                        help='Disable ANSI color output.')

    args = parser.parse_args()

    if not os.path.exists(args.infile):
        print(f"Error: File not found: {args.infile}", file=sys.stderr)
        sys.exit(1)

    # Determine if we should use color
    use_color = False
    if args.color is True:
        use_color = True
    elif args.color is None and sys.stdout.isatty():
        use_color = True

    try:
        with open(args.infile, 'rt', encoding='utf-8') as f:
            cardstats = [line.strip().split('|') for line in f if len(line.split('|')) >= 4]
    except Exception as e:
        print(f"Error reading {args.infile}: {e}", file=sys.stderr)
        sys.exit(1)

    nonempty, name_avg, name_dupes, card_avg, card_dupes = calculate_stats(cardstats)

    if nonempty == 0:
        print(f"Notice: No valid distance data found in {args.infile}.", file=sys.stderr)
        return

    # Unified UI Header
    utils.print_header("DISTANCE SUMMARY", count=nonempty, use_color=use_color)

    # Table Output
    header = ["Category", "Avg Similarity", "Duplicates", "Distribution"]
    if use_color:
        header = [utils.colorize(h, utils.Ansi.BOLD + utils.Ansi.UNDERLINE) for h in header]

    rows = [header]

    # Name Similarity Row
    name_pct = name_avg * 100
    name_bar = datalib.get_bar_chart(name_pct, use_color, color=utils.Ansi.BOLD + utils.Ansi.CYAN)
    name_label = "Names"
    if use_color:
        name_label = utils.colorize(name_label, utils.Ansi.BOLD + utils.Ansi.CYAN)
    rows.append([
        name_label,
        f"{name_avg:7.4f}",
        datalib.color_count(name_dupes, use_color, utils.Ansi.BOLD + utils.Ansi.YELLOW),
        name_bar
    ])

    # Card Similarity Row
    card_pct = card_avg * 100
    card_bar = datalib.get_bar_chart(card_pct, use_color, color=utils.Ansi.BOLD + utils.Ansi.GREEN)
    card_label = "Cards"
    if use_color:
        card_label = utils.colorize(card_label, utils.Ansi.BOLD + utils.Ansi.GREEN)
    rows.append([
        card_label,
        f"{card_avg:7.4f}",
        datalib.color_count(card_dupes, use_color, utils.Ansi.BOLD + utils.Ansi.YELLOW),
        card_bar
    ])

    datalib.add_separator_row(rows)
    datalib.printrows(datalib.padrows(rows, aligns=['l', 'r', 'r', 'l']), indent=4)
    print()

if __name__ == "__main__":
    main()
