#!/usr/bin/env python3
import sys
import os
import argparse
import json
import csv

# Add lib directory to path
libdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), '../lib')
sys.path.append(libdir)

import utils
import datalib

def calculate_stats(data):
    """Calculates average similarity and duplicate counts for names and cards."""
    nonempty = len(data)
    if nonempty == 0:
        return 0, 0.0, 0, 0.0, 0
    # data is [index, name, name_sim, card_sim]
    try:
        name_avg = sum(float(item[2]) for item in data) / nonempty
        name_dupes = sum(float(item[2]) == 1.0 for item in data)
        card_avg = sum(float(item[3]) for item in data) / nonempty
        card_dupes = sum(float(item[3]) == 1.0 for item in data)
    except (ValueError, IndexError):
        return 0, 0.0, 0, 0.0, 0

    return nonempty, name_avg, name_dupes, card_avg, card_dupes

def main():
    parser = argparse.ArgumentParser(
        description="Summarize the distance statistics (similarity ratios) produced by scripts/distances.py.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This tool analyzes the output of distances.py to provide a high-level overview of how closely
a generated dataset matches the official Magic: The Gathering card pool.

Distance metrics (Similarity ratios):
  - Name Similarity: How closely the generated names match existing ones (1.0 = exact duplicate).
  - Semantic Similarity: How closely the card's mechanical meaning matches existing cards.

Usage Examples:
  # Summarize results from a distance analysis
  python3 scripts/sum.py distances.txt

  # Export distance summary to JSON or CSV
  python3 scripts/sum.py distances.txt -o summary.json
  python3 scripts/sum.py distances.txt --csv -o summary.csv

  # Preview distance summary statistics without writing output files (dry-run mode)
  python3 scripts/sum.py distances.txt --dry-run
"""
    )

    # Group: Input / Output
    io_group = parser.add_argument_group('Input / Output')
    io_group.add_argument('infile', nargs='?', default='-',
                        help='The distance data file generated by scripts/distances.py. Defaults to distances.txt if available, or standard input (-).')
    io_group.add_argument('-o', '--outfile', default=None,
                        help='Path to save summary results. If omitted, results print to stdout.')

    # Group: Processing Options
    proc_group = parser.add_argument_group('Processing Options')
    proc_group.add_argument('-p', '--preview', '--dry-run', dest='dry_run', action='store_true',
                        help='Print a dry run summary of distance analysis statistics (file source, entry count, average similarities, and duplicate counts) to standard output without creating output files.')

    # Group: Output Format
    fmt_group_title = parser.add_argument_group('Output Format')
    fmt_group = fmt_group_title.add_mutually_exclusive_group()
    fmt_group.add_argument('-t', '--table', action='store_true', help='Generate a formatted table (Default).')
    fmt_group.add_argument('-j', '--json', action='store_true', help='Generate a structured JSON summary.')
    fmt_group.add_argument('--csv', action='store_true', help='Generate a CSV summary.')

    # Group: Logging & Debugging
    debug_group = parser.add_argument_group('Logging & Debugging')
    color_group = debug_group.add_mutually_exclusive_group()
    color_group.add_argument('--color', action='store_true', default=None,
                        help='Force enable ANSI color output.')
    color_group.add_argument('--no-color', action='store_false', dest='color',
                        help='Disable ANSI color output.')

    args = parser.parse_args()

    # Smart defaulting for interactive sessions vs piped stdin
    if args.infile == '-' or args.infile is None:
        if sys.stdin.isatty():
            default_file = 'distances.txt'
            if os.path.exists(default_file):
                args.infile = default_file
            else:
                parser.print_help(sys.stderr)
                sys.exit(1)

    # Auto-detect format from outfile extension
    if not (args.json or args.csv or args.table):
        if args.outfile:
            if args.outfile.endswith('.json'):
                args.json = True
            elif args.outfile.endswith('.csv'):
                args.csv = True
            else:
                args.table = True
        else:
            args.table = True

    # Determine if we should use color
    use_color = False
    if args.color is True:
        use_color = True
    elif args.color is None and not (args.json or args.csv) and sys.stdout.isatty():
        use_color = True

    try:
        if args.infile == '-':
            cardstats = [line.strip().split('|') for line in sys.stdin if len(line.split('|')) >= 4]
        else:
            if not os.path.exists(args.infile):
                print(f"Error: File not found: {args.infile}", file=sys.stderr)
                sys.exit(1)
            with open(args.infile, 'rt', encoding='utf-8') as f:
                cardstats = [line.strip().split('|') for line in f if len(line.split('|')) >= 4]
    except Exception as e:
        filename = args.infile if args.infile != '-' else 'stdin'
        print(f"Error reading {filename}: {e}", file=sys.stderr)
        sys.exit(1)

    nonempty, name_avg, name_dupes, card_avg, card_dupes = calculate_stats(cardstats)

    if args.dry_run:
        source_name = args.infile if args.infile != '-' else 'stdin'
        dest_name = args.outfile if args.outfile else 'Console (sys.stdout)'
        print(f"Dry Run Summary: Distance data loaded from {source_name} ({nonempty} valid entries).")
        print(f"Name Similarity Avg: {name_avg:.4f} (Exact Duplicates: {name_dupes})")
        print(f"Card Similarity Avg: {card_avg:.4f} (Exact Duplicates: {card_dupes})")
        print(f"Output Destination: {dest_name}")
        return

    if nonempty == 0:
        print(f"Notice: No valid distance data found in {args.infile}.", file=sys.stderr)
        return

    output_f = sys.stdout
    if args.outfile:
        output_f = open(args.outfile, 'w', encoding='utf-8')

    try:
        if args.json:
            result = {
                'total_records': nonempty,
                'name_similarity': {
                    'average': round(name_avg, 4),
                    'duplicates': name_dupes
                },
                'semantic_similarity': {
                    'average': round(card_avg, 4),
                    'duplicates': card_dupes
                }
            }
            output_f.write(json.dumps(result, indent=2) + '\n')
        elif args.csv:
            writer = csv.writer(output_f)
            writer.writerow(['Category', 'Avg Similarity', 'Duplicates'])
            writer.writerow(['Names', f"{name_avg:.4f}", name_dupes])
            writer.writerow(['Cards', f"{card_avg:.4f}", card_dupes])
        else:
            # Unified UI Header
            utils.print_header("DISTANCE SUMMARY", count=nonempty, use_color=use_color, file=output_f)

            # Table Output
            header = ["Category", "Avg Similarity", "Duplicates", "Distribution"]
            if use_color:
                header = [utils.colorize(h, utils.Ansi.BOLD + utils.Ansi.UNDERLINE) for h in header]

            rows = [header]

            # Name Similarity Row
            name_pct = name_avg * 100
            name_bar = datalib.get_bar_chart(name_pct, use_color, color=utils.Ansi.BOLD + utils.Ansi.CYAN)
            name_label = "Names"
            if use_color:
                name_label = utils.colorize(name_label, utils.Ansi.BOLD + utils.Ansi.CYAN)
            rows.append([
                name_label,
                f"{name_avg:7.4f}",
                datalib.color_count(name_dupes, use_color, utils.Ansi.BOLD + utils.Ansi.YELLOW),
                name_bar
            ])

            # Card Similarity Row
            card_pct = card_avg * 100
            card_bar = datalib.get_bar_chart(card_pct, use_color, color=utils.Ansi.BOLD + utils.Ansi.GREEN)
            card_label = "Cards"
            if use_color:
                card_label = utils.colorize(card_label, utils.Ansi.BOLD + utils.Ansi.GREEN)
            rows.append([
                card_label,
                f"{card_avg:7.4f}",
                datalib.color_count(card_dupes, use_color, utils.Ansi.BOLD + utils.Ansi.YELLOW),
                card_bar
            ])

            datalib.add_separator_row(rows)
            datalib.printrows(datalib.padrows(rows, aligns=['l', 'r', 'r', 'l']), indent=4, file=output_f)
            print(file=output_f)
    finally:
        if args.outfile:
            output_f.close()

if __name__ == "__main__":
    main()
